OFFI-134: Add email client with IMAP email download, background sync and content types
Lombiq/Orchard-Email-Client pull request #1
Opened 2024-12-18 07:04 UTC by barthamark

2024-12-18 16:50 UTC, wAsnk commented on Lombiq.EmailClient/Lombiq.EmailClient.csproj
> +    <Title>Lombiq Email Client</Title>
```suggestion
    <Title>Lombiq Email Client for Orchard Core</Title>
```

2024-12-18 16:50 UTC, wAsnk commented on Lombiq.EmailClient/Lombiq.EmailClient.csproj
> +    <Copyright>Copyright © 2021, Lombiq Technologies Ltd.</Copyright>
Year will be probably 2025

2024-12-18 16:50 UTC, wAsnk commented on Lombiq.EmailClient/Lombiq.EmailClient.csproj
> +    <PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
https://lombiq.atlassian.net/wiki/spaces/DEV/pages/2609840133/Preparing+a+.NET+project+to+be+published+on+NuGet#:~:text=All%20of%20our%20open%2Dsource%20packages%20use

> All of our open-source packages use the BSD-3-Clause license, using the package license expression ensures that we don’t have to maintain license files for each of our packages unnecessarily. However, keep a License.md file in the repository root for GitHub’s license detection.

2025-02-11 23:19 UTC, sarahelsaig requested changes

2025-02-11 23:19 UTC, sarahelsaig commented on Lombiq.EmailClient/Manifest.cs
> +)]
Since this doesn't make sense by itself without one of the dependency features, wouldn't it be better to set `EnabledByDependencyOnly` to true?

2025-02-11 23:19 UTC, sarahelsaig commented on Lombiq.EmailClient/Models/AttachmentMetadata.cs
> +    /// Gets or sets the filename of the attachment.
```suggestion
    /// Gets or sets the file name of the attachment.
```

2025-02-11 23:19 UTC, sarahelsaig commented on Lombiq.EmailClient/Models/AttachmentMetadata.cs
> +    /// Gets or sets the MIME type of the attachment (e.g., "application/pdf", "image/jpeg").
At first I was going to suggest to use inline code element when referring to a technical identifier like this: `(e.g., <c>application/pdf</c>, <c>image/jpeg</c>)`

But in this specific case use `<see cref="MediaTypeNames.Application.Pdf"/>` from `System.Net.Mime`.

2025-02-11 23:19 UTC, sarahelsaig commented on Lombiq.EmailClient/Models/EmailSyncSettings.cs
> +public class EmailSyncSettings
I suggest always descending from the `Lombiq.HelpfulLibraries.Common.Utilities.ICopier<T>` interface for any type with a `void CopyTo(T)` method. (So `EmailSyncSettings` and `ImapSettings`.)

I don't think it's strictly necessary here but would be good future proofing anyway.

2025-02-11 23:19 UTC, sarahelsaig commented on Lombiq.EmailClient/Navigation/EmailSyncAdminMenu.cs
> +        if (!string.Equals(name, "admin", StringComparison.OrdinalIgnoreCase)) return ValueTask.CompletedTask;
Instead of this boilerplate, inherit from `Lombiq.HelpfulLibraries.OrchardCore.Navigation.AdminMenuNavigationProviderBase` rather than `INavigationProvider`. Then you can override the `Build` method and no need for this check or for the `return ValueTask.CompletedTask` at the end, so you can use an expression body.

2025-02-11 23:19 UTC, sarahelsaig commented on Lombiq.EmailClient/Navigation/ImapAdminMenu.cs
> +public sealed class ImapAdminMenu : INavigationProvider
Same here, inherit from `AdminMenuNavigationProviderBase`.

2025-02-11 23:19 UTC, sarahelsaig commented on Lombiq.EmailClient/Services/ImapEmailClient.cs
> +            attachment.ContentDisposition.FileName == attachmentMetadata.FileName);
Since these are file names I have to ask: is this intentionally a case sensitive check?

2025-02-11 23:19 UTC, sarahelsaig commented on Lombiq.EmailClient/Services/ImapEmailClient.cs
> +        _imapSettings.Host.Contains("localhost", StringComparison.OrdinalIgnoreCase);
Apparently there is a canonical way to check if an `IPAddress` is localhost/loopback, you just have to convert the host name into IP first like this: `Dns.GetHostAddresses(host).Any(IPAddress.IsLoopback)`

2025-02-12 11:14 UTC, barthamark commented on Lombiq.EmailClient/Lombiq.EmailClient.csproj
> +    <PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
Yeah I didn't worry about all these because there'll be a separate issue for integrating it to OSOCE which will include a lot of stuff like reusable UI test, sample project, extensive documentation, and everything needed for nuget publish, like this. Anyway, I add this file now, I'm just spamming you with emails unnecessarily. <3

2025-02-12 11:15 UTC, barthamark commented on Lombiq.EmailClient/Lombiq.EmailClient.csproj
> +    <PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
Wait... there's a License.md file already.

2025-02-12 11:28 UTC, barthamark commented on Lombiq.EmailClient/Services/ImapEmailClient.cs
> +            attachment.ContentDisposition.FileName == attachmentMetadata.FileName);
Didn't think about it, but theoretically, it's possible to attach littlekitty.png and LittleKitty.png to the same email if the email client allows it therefore we can be in a situation where IMAP retrieves both.

2025-02-12 14:41 UTC, sarahelsaig approved these changes

2025-02-18 16:48 UTC, merged